- block:
    - name: Download the PlexTraktSync script
      git:
        repo: https://github.com/Taxel/PlexTraktSync
        dest: '{{ script_location_path }}'
        force: true

    - name: Check if project virtual environment exists
      command: pipenv --venv
      args:
        chdir: '{{ script_location_path }}'
      register: pipenv_venv_result
      changed_when: false
      failed_when: false

    - name: Remove current project virtual environment
      command: pipenv --rm
      args:
        chdir: '{{ script_location_path }}'
      when: "'virtualenvs/PlexTraktSync' in pipenv_venv_result.stdout"

    - name: Create new project virtual environment and install dependencies
      command: pipenv --bare install
      args:
        chdir: '{{ script_location_path }}'
      environment:
        LANG: en_GB.UTF-8

    - name: Copy Plex credentials file to project configuration directory
      copy:
        src: .env
        dest: '{{ script_location_path }}/.env'

    - name: Copy Trakt.tv credentials file to project configuration directory
      copy:
        src: .pytrakt.json
        dest: '{{ script_location_path }}/.pytrakt.json'

    - name: Copy configuration file to project configuration directory
      copy:
        src: config.json
        dest: '{{ script_location_path }}/config.json'

  vars:
    ansible_become_user: '{{ config_admin_user_name }}'
    script_location_path: /volume1/homes/{{ config_admin_user_name }}/.local/scripts/PlexTraktSync
