- name: Update '~/.inputrc' configuration for user '{{ config_role_user_name }}'
  template:
    src: inputrc.j2
    dest: '{{ config_role_user_home }}/.inputrc'
    owner: '{{ config_role_user_name }}'
    group: '{{ config_role_user_name }}'
    mode: '0644'
