- name: Install 'unattended-upgrades' package and dependencies
  apt:
    pkg:
      - bsd-mailx
      - unattended-upgrades

- name: Update '/etc/apt/apt.conf.d/50unattended-upgrades' configuration
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Update '/etc/apt/apt.conf.d/20auto-upgrades' configuration
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
