- name: Update '~/.dircolors' configuration for user '{{ config_role_user_name }}'
  template:
    src: dircolors.j2
    dest: '{{ config_role_user_home }}/.dircolors'
    owner: '{{ config_role_user_name }}'
    group: '{{ config_role_user_name }}'
    mode: '0644'
