- name: Update pinning priorities for multiple releases/repositories
  template:
    src: '{{ file }}.j2'
    dest: /etc/apt/preferences.d/{{ file }}
    owner: root
    group: root
    mode: '0644'
  with_items:
    - stable-security.pref
    - stable-updates.pref
    - stable.pref
    - testing.pref
  loop_control:
    loop_var: file

- name: Setup 'testing' repository for Debian
  apt_repository:
    repo: deb http://deb.debian.org/debian bookworm main contrib non-free
    update_cache: true
    filename: testing
    mode: '0644'
    state: present
