- name: Configure 'testing' repository packages pin-priority
  template:
    src: debian-testing.pref.j2
    dest: /etc/apt/preferences.d/debian-testing.pref
    mode: '0644'

- name: Setup 'testing' repository for Raspberry Pi OS
  apt_repository:
    repo: deb http://raspbian.raspberrypi.org/raspbian testing main
    update_cache: true
    filename: raspbian-testing
    mode: '0644'
    state: present

- name: Install 'wireguard' package
  apt:
    pkg: wireguard

- name: Enable IP packet forwarding for IPv4
  lineinfile:
    path: /etc/sysctl.conf
    regexp: ^#net.ipv4.ip_forward=1
    line: net.ipv4.ip_forward=1
  notify:
    - Reboot system
