- name: Add a trusted key for the Tailscale repository
  apt_key:
    url: https://pkgs.tailscale.com/stable/raspbian/buster.gpg
    state: present

- name: Setup 'buster' repository for Tailscale
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/raspbian buster main
    update_cache: true
    filename: tailscale
    mode: '0644'
    state: present

- name: Install 'tailscale' package
  apt:
    pkg: tailscale

- name: Authenticate and connect this machine to private Tailscale network
  command: >
    tailscale up
      --authkey {{ config_tailscale_pre_auth_key }}
      --advertise-routes=10.0.10.0/24,10.0.80.0/24,10.0.90.0/24
      --advertise-exit-node
      --accept-dns=false
  changed_when: false

- name: Enable IP packet forwarding for IPv4/IPv6
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '{{ file.regexp }}'
    line: '{{ file.line }}'
    backrefs: true
  with_items:
    - { regexp: ^#(net.ipv4.ip_forward=1), line: '\1' }
    - { regexp: ^#(net.ipv6.conf.all.forwarding=1), line: '\1' }
  loop_control:
    loop_var: file
  notify:
    - Reboot system
