- name: Install 'docker.io' package (testing)
  apt:
    pkg: docker.io
    default_release: testing
    autoclean: true
    autoremove: true

- name: Add '{{ config_admin_user_name }}' user to 'docker' group
  user:
    name: '{{ config_admin_user_name }}'
    groups: 'docker'
    append: true

- name: Add a cronjob to prune all unused Docker data every week
  cron:
    name: 'prune unused Docker data'
    minute: '0'
    hour: '3'
    weekday: '0'
    job: 'cronic docker system prune --all --force'
