- name: Update '~/.profile' configuration for user '{{ config_role_user_name }}'
  template:
    src: profile.j2
    dest: '{{ config_role_user_home }}/.profile'
    owner: '{{ config_role_user_name }}'
    group: '{{ config_role_user_name }}'
    mode: '0644'
