cache:
  path: $PTS_CACHE_DIR/.cache/trakt
excluded-libraries:
  - Samples
logging:
  append: true
sync:
  plex_to_trakt:
    collection: false
    ratings: false
    watched_status: true
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: false
watch:
  add_collection: true
  remove_collection: true
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb
