- name: Update '~/.profile' configuration for user '{{ config_admin_user_name }}'
  copy:
    src: profile
    dest: '/home/{{ config_admin_user_name }}/.profile'
    owner: '{{ config_admin_user_name }}'
    group: '{{ config_admin_user_name }}'
    mode: '0644'
