- name: Update '~/.nanorc' configuration for user '{{ config_role_user_name }}'
  template:
    src: nanorc.j2
    dest: '{{ config_role_user_home }}/.nanorc'
    owner: '{{ config_role_user_name }}'
    group: '{{ config_role_user_name }}'
    mode: '0644'
