- name: Update '~/.aliases' configuration for user '{{ config_role_user_name }}'
  template:
    src: aliases.j2
    dest: '{{ config_role_user_home }}/.aliases'
    owner: '{{ config_role_user_name }}'
    group: '{{ config_role_user_name }}'
    mode: '0644'
