- hosts: HYPERCUBE

  tasks:
    - block:
        - name: Configure base system settings and services
          include_role:
            name: '{{ item }}'
          with_items:
            - distro/synology/base/setup-ansible-dependencies

        - name: Install Docker container applications (Common)
          include_role:
            name: '{{ role }}'
          loop:
            - distro/synology/software/containers/plex
            - distro/synology/software/containers/plex-trakt-sync
            - distro/synology/software/containers/watchtower
          loop_control:
            loop_var: role

        - name: Install Docker container applications (Servarr)
          include_role:
            name: distro/synology/software/containers/servarr
          loop:
            - { name: 'Bazarr', key: 'en', ports: ['23080:6767'], memory: '512M' }
            - { name: 'Bazarr', key: 'pt', ports: ['23081:6767'], memory: '512M' }
            - { name: 'NZBHydra2', ports: ['22080:5076'], memory: '512M', media_volume: false }
            - { name: 'Overseerr', ports: ['26080:5055'], memory: '512M', media_volume: false }
            - { name: 'Radarr', ports: ['24080:7878'] }
            - { name: 'SABnzbd', ports: ['21080:8080'], memory: '2G' }
            - { name: 'Sonarr', ports: ['25080:8989'] }
            - { name: 'Tautulli', ports: ['27080:8181'], memory: '512M', media_volume: false }
          loop_control:
            loop_var: container

      vars:
        ansible_user: '{{ config_admin_user_name }}'
        ansible_become_pass: '{{ config_admin_user_pass }}'

      become: true
