- hosts: POLYMERBOX

  pre_tasks:
    - block:
        - name: Update known public keys for remote host
          include_role:
            name: machine/local/ssh/update-known-hosts

        - block:
            - block:
                - name: Create remote host administrator user account
                  include_role:
                    name: distro/debian/accounts/create-admin-user
                - meta: reset_connection

              vars:
                ansible_user: '{{ config_default_user_name }}'
                ansible_ssh_pass: '{{ config_default_user_pass }}'

            - block:
                - name: Delete remote host default user account
                  include_role:
                    name: distro/debian/accounts/delete-default-user

              vars:
                ansible_user: '{{ config_admin_user_name }}'
                ansible_become_pass: '{{ config_admin_user_pass }}'

          become: true

      tags:
        - bootstrap
        - never

  tasks:
    - block:
        - name: Configure base system settings and services
          include_role:
            name: '{{ item }}'
          with_items:
            - distro/raspbian/base/configure-system
            - distro/debian/base/configure-localization
            - distro/debian/base/configure-sshd
            - distro/raspbian/base/configure-unattended-upgrades
            - distro/raspbian/base/configure-testing-repository

        - name: Upgrade distribution software and kernel
          include_role:
            name: distro/debian/base/upgrade-system

        - name: Setup 'root' user profile
          include_role:
            name: '{{ item }}'
          with_items:
            - linux/dotfiles/aliases
            - linux/dotfiles/dircolors
            - linux/dotfiles/inputrc
            - linux/dotfiles/nanorc
            - linux/dotfiles/profile
            - linux/shell/switch-from-bash-to-zsh
          vars:
            config_role_user_name: root
            config_role_user_home: /root

        - name: Setup '{{ config_admin_user_name }}' user profile
          include_role:
            name: '{{ item }}'
          with_items:
            - linux/dotfiles/aliases
            - linux/dotfiles/dircolors
            - linux/dotfiles/inputrc
            - linux/dotfiles/nanorc
            - linux/dotfiles/profile
            - linux/shell/switch-from-bash-to-zsh
          vars:
            config_role_user_name: '{{ config_admin_user_name }}'
            config_role_user_home: /home/{{ config_admin_user_name }}

        - name: Install additional software
          include_role:
            name: '{{ item }}'
          with_items:
            - distro/raspbian/software/install-acme.sh
            - distro/raspbian/software/install-borgbackup
            - distro/raspbian/software/install-cloudflared
            - distro/raspbian/software/install-docker
            - distro/raspbian/software/install-postfix
            - distro/raspbian/software/install-tailscale

        - name: Install Docker container applications
          vars:
            config_role_container_name: "{{ item | basename | replace('docker-', '') }}"
          include_role:
            name: '{{ item }}'
          with_items:
            - machine/polymerbox/software/docker-traefik
            - machine/polymerbox/software/docker-adguard-home
            - machine/polymerbox/software/docker-unifi-controller
            - machine/polymerbox/software/docker-watchtower

      vars:
        ansible_user: '{{ config_admin_user_name }}'
        ansible_become_pass: '{{ config_admin_user_pass }}'

      become: true

  post_tasks:
    - block:
        - name: Upgrade distribution and additional software
          include_role:
            name: '{{ item }}'
            apply:
              tags:
                - upgrade
          with_items:
            - distro/debian/base/upgrade-system
          tags:
            - upgrade
            - never

        - name: Upgrade Docker container applications
          vars:
            config_role_container_name: "{{ item | basename | replace('docker-', '') }}"
          include_role:
            name: '{{ item }}'
            apply:
              tags:
                - never
          with_items:
            - machine/polymerbox/software/docker-unifi-controller
          tags:
            - upgrade
            - never

      vars:
        ansible_user: '{{ config_admin_user_name }}'
        ansible_become_pass: '{{ config_admin_user_pass }}'

      become: true

      tags:
        - upgrade
        - never
